# Generated by Django 2.0.2 on 2018-02-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('article', 'header', 'title'),
    ]
